name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build APK with Buildozer Action
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
      - name: Copy APK to artifact
        run: |
          mkdir -p dist_apk
          APK_PATH=$(find bin ./app/bin -name "*.apk" | head -n 1)
          if [ -n "$APK_PATH" ]; then cp "$APK_PATH" dist_apk/TTZAlarmAndroid.apk; fi
      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: dist_apk/
