name: Build iOS Xcode Project

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          brew install python3 autoconf automake
      - name: Set up Python venv
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install Cython kivy ffpyplayer kivy-ios
      - name: Build Kivy-iOS project
        run: |
          source venv/bin/activate
          python -m kivy_ios.toolchain build python3
          python -m kivy_ios.toolchain build kivy ffpyplayer
          python -m kivy_ios.toolchain create ttzalarm main.py
      - name: Archive Xcode project
        run: |
          cp alarm.flac ttzalarm-ios/
          tar czf TTZAlarmiOS-xcode-project.tar.gz ttzalarm-ios
      - uses: actions/upload-artifact@v4
        with:
          name: ios-xcode-project
          path: TTZAlarmiOS-xcode-project.tar.gz
